client/src/App.js, client/src/components/pages/Contact.js, client/src/components/pages/Search.js, client/src/styles/index.css, client/src/styles/pages.css
Hey guys I completed the styling for contact page and deleted unnecessary codes in the Contact.js module. Please feel free to test it out!
=> completed contact page styling and functions

client/src/components/common/Navigation.js, client/src/components/pages/About.js, client/src/components/pages/Memebership.js, client/src/styles/pages.css
Hey guys! I finished the front end content and styling of the membership page.
=> added styling and content to membership page

client/src/App.js, client/src/components/pages/Memebership.js, client/src/components/pages/Search.js, client/src/styles/pages.css
Hey guys I added to the search page!
=> added to search page and search page styling

client/src/App.js, client/src/components/pages/Dashboard.js, client/src/styles/pages.css
Hey guys I added codes to the dashboard page!
=> added to dashboard page and styling

client/src/components/UserContext.js, client/src/components/common/Navigation.js, client/src/components/jobs/JobResultCard.js, client/src/components/jobs/JobResults.js, client/src/components/pages/Cancel.js, client/src/components/pages/Login.js, client/src/components/pages/Search.js, client/src/index.js, client/src/styles/job.css, client/src/styles/pages.css, server/schemas/resolvers.js, server/server.js
Hey guys I added a UserContext component to provide user's login status so that we can use it to correctly display navbar links: when the user is NOT logged in he won't see the dashboard and membership links.
=> added useContext for user's login status so navbar reflects login status

client/src/components/auth/LoginForm.js, client/src/components/auth/SignupForm.js, client/src/components/pages/About.js, client/src/components/pages/Login.js, client/src/components/pages/Memebership.js, client/src/utils/mutations.js, package-lock.json, package.json, server/config/connection.js
Added login and signup functionality, render login/register on login page, fixed membership/about page typo, fixed database connection, change project name
=> Login/Signup Functionality, Login Page Rendering, Membership/About Page Typo, Database Connection, Project Name

client/src/components/UserContext.js, client/src/components/common/Navigation.js, client/src/components/jobs/JobResultCard.js, client/src/components/pages/About.js, client/src/components/pages/Dashboard.js, client/src/components/pages/Setting.js, client/src/components/pages/Success.js, client/src/styles/pages.css, server/schemas/resolvers.js
Hey guys I tweaked the nav link a little to make sure only paid members get to save jobs and see their dashboard
=> Fred css react apr 22

client/src/components/UserContext.js, client/src/components/jobs/SavedJobCard.js, client/src/components/pages/Dashboard.js, client/src/components/pages/Setting.js, client/src/styles/job.css, client/src/styles/pages.css
Hey guys I added content and styling to dashboard page. Not complete yet so I'll keep going
=> added content and styling to dashboard

client/src/components/UserContext.js, client/src/components/common/Navigation.js, client/src/components/jobs/JobResultCard.js, client/src/components/jobs/SavedJobCard.js, client/src/components/jobs/SavedJobs.js, client/src/components/pages/Dashboard.js, client/src/components/pages/Setting.js, client/src/styles/job.css, client/src/styles/pages.css
Hey guys I basically completed the dashboard layout and some basically front-end functionality:
When you click on SETTING at the bottom of the dashboard, the user setting section will appear, allowing users to look at all their info, and if they wish to edit anything, they can press the edit button , which will turn all the textareas editable, and when they're done, they can just press save changes so the textareas become readonly again - we'll need to insert backend functions in the save changes handler so that the user's info is updated in the database.
The user can also conveniently click on Copy resume or copy cover letter to copy the text into their browser clipboard.
=> Fred react css apr 23

client/src/styles/footer.css, server/schemas/resolvers.js, server/schemas/typeDefs.js
Hey guys, I fixed the bug in the setting section where the cover letter isn't updating to the database. It works now.
=> fixed cover letter saving bug in setting section

client/src/components/pages/Setting.js, client/src/styles/pages.css, client/src/utils/queries.js, server/schemas/typeDefs.js
Hey guys I added codes to verify user password before updating the password. Now users must enter their old password correctly before they can update their password in the setting page
=> added password-matching process before updating user password

client/src/components/pages/Setting.js, client/src/styles/pages.css, server/schemas/resolvers.js
Hey guys I fixed a typo in the Stripe checkout mutation in the resolver. Now the Stripe checkout should work properly with our .env working !
=> changed resolver where Stripe checkout mutation is

client/src/components/jobs/JobResultCard.js, client/src/components/pages/Search.js
Put back important codes so job search works
=> added codes back in so findJobs() works

client/src/components/common/Footer.js, client/src/components/jobs/JobResultCard.js, client/src/components/pages/Search.js, client/src/styles/footer.css, client/src/styles/job.css
Hey guys I added a back to top button in the footer so when the search result makes the page very long users can click on it to get back up!
=> Fred react css apr 25

client/src/components/jobs/JobResultCard.js, client/src/styles/job.css, client/src/styles/pages.css
Hey guys I finished styling the result card and formatted how the estimated salary is displayed: now the salary is founded down to closest integer, and if max salary is the same as min salary only one salary amount will display.
=> formatted salary amounts and styled result cards

client/src/App.js, client/src/components/auth/LoginForm.js, client/src/components/common/Header.js, client/src/components/common/Layout.js, client/src/components/common/Navigation.js, client/src/components/jobs/SavedJobs.js, client/src/components/pages/Dashboard.js
Hey guys Michael is gonna try and fix the routing issue so be advised that the front is under construction atm
=> fixing routing issue

client/src/App.js, client/src/components/common/Footer.js, client/src/components/common/Header.js, client/src/components/common/Layout.js, client/src/components/common/Navigation.js, client/src/components/pages/About.js, client/src/components/pages/Cancel.js, client/src/components/pages/Contact.js, client/src/components/pages/Dashboard.js, client/src/components/pages/Login.js, client/src/components/pages/Memebership.js, client/src/components/pages/Search.js, client/src/components/pages/Setting.js, client/src/components/pages/Success.js, client/src/index.js
I went through and fixed styling issues, got rid of unused variables, and fixed any other potential issues with coding conventions
=> Styling and coding conventions

client/src/components/pages/Success.js
Hey guys Aviva pointed out an important bug in the payment process so I fixed it. Now upon success page load, the user's payment status will be updated.
=> make user's membership status update upon success page load

client/src/components/jobs/JobResultCard.js, client/src/components/jobs/SavedJobCard.js, client/src/components/jobs/SavedJobs.js, client/src/utils/mutations.js, server/schemas/resolvers.js
Hey guys I added the codes for delete job button so now users can remove a saved job from their dashboard
=> added delete job functionality to user's dashboard

client/src/components/jobs/JobResultCard.js, client/src/components/pages/Search.js, client/src/styles/pages.css
Hey guys I added the loading banner for the search page and a "job progress updated" alert for the saved jobs.
There is a bug where once the job progress drop-down menu is saved for the first time, it doesn't allow us to updated it a second time( The job notes can be updated multiple times)
=> Fred react css apr 26

client/src/components/common/Footer.js, client/src/components/jobs/JobResultCard.js, client/src/components/jobs/SavedJobCard.js, client/src/styles/footer.css, client/src/styles/job.css
Hey guys I added a share job button next to each Save Job button so that paid members can email job listing details to either themselves or friends!
=> Fred css react apr 27

client/package.json, client/src/components/pages/Setting.js
Hey guys after we refactored the settings page I reformatted the password update process for the front end!
=> refactored password update process

client/src/components/pages/Setting.js, server/schemas/resolvers.js
Hey guys I changed the success and cancel URL's of the stripe checkout process to ONLY our deployed App's root URL so that when users successfully paid or cancel they get directly to the correct URL
=> updated Stripe success and cancel URL

client/src/styles/footer.css
Hey guys I removed the install button for mobile viewports coz the button doesn't work for cellphones anyway
=> Fred css react apr 28

README.md
Hey guys I added in the deploy app's URL and updated the GitHub repo's URL in our README file
=> updated GH repo URL in README and added in deployed app's URL

README.md, client/src/components/common/Footer.js, client/src/styles/footer.css, client/src/styles/pages.css
Hey guys just some final touches on css
=> final touches on css

client/src/styles/footer.css, client/src/styles/header.css
Hey guys one last push - added glow effect to active nav link for a some nice hightlight effect
=> added glow effect to active nav links:

client/src/styles/footer.css, client/src/styles/header.css
Hey guys final touches on css- added animation to header and footer for  pixel-game effect.
=> added header and footer animation

client/src/styles/pages.css
Hey guys last minute bug killing - found a css bug that was letting users access the nav links buttons and footer buttons on success and cancel pages. fixed.
=> fixed success and cancel pages z-index issues

client/src/styles/pages.css
Hey guys one last change on the bug fix
=> updated bug fix on success and cancel pages
